spring:
  application:
    name: RIDE-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://mysql:3306/rideshare?createDatabaseIfNotExist=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rideshare}
    password: ${RABBITMQ_PASSWORD:rideshare123}

server:
  port: ${PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-service:8761/eureka}

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true