spring:
  application:
    name: AUTH-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://mysql:3306/rideshare?createDatabaseIfNotExist=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rideshare}
    password: ${RABBITMQ_PASSWORD:rideshare123}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}

server:
  port: ${PORT:8081}

jwt:
  validity:
    accessToken: 3600000
    refreshToken: 2592000000
  secret: ${JWT_SECRET:jwt-secret-code}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:ride-sharing-platform-auth.onrender.com}
    prefer-ip-address: false
    secure-port-enabled: true
    secure-port: 443
    non-secure-port-enabled: false

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG