spring:
  application:
    name: AUTH-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/rideshare?createDatabaseIfNotExist=true
    username: root
    password: root

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rideshare
    password: rideshare123

server:
  port: 8081

jwt:
  validity:
    accessToken: 3600000
    refreshToken: 2592000000
  secret: jwt-secret-code

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG