spring:
  application:
    name: NOTIFICATION-SERVICE

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rideshare}
    password: ${RABBITMQ_PASSWORD:rideshare123}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${BREVO_USERNAME}
    password: ${BREVO_SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:ride-sharing-platform-notif.onrender.com}
    prefer-ip-address: false
    secure-port-enabled: true
    secure-port: 443
    non-secure-port-enabled: false