spring:
  application:
    name: NOTIFICATION-SERVICE

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rideshare}
    password: ${RABBITMQ_PASSWORD:rideshare123}

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${BREVO_USERNAME}
    password: ${BREVO_SMTP_KEY}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-service:8761/eureka}

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true